---
- name: Install prerequisites
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python3
      - python3-pip
    state: present

- name: Download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
    dest: /tmp/get-pip.py

- name: Install python-pip
  command: python3 /tmp/get-pip.py --user
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/pip"
  ignore_errors: yes

- name: Add local bin to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH=$PATH:{{ ansible_env.HOME }}/.local/bin'
    state: present

- name: Install docker python module
  pip:
    name: docker
    extra_args: --user
    executable: "{{ ansible_env.HOME }}/.local/bin/pip"

- name: Add Docker CE repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Remove old versions of Docker
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Install Docker CE
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable the Docker daemon
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Add remote user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'


