---
- name: "Generation du docker-compose file"
  template:
    src: "docker-compose-pgadmin.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose-pgadmin.yml
    mode: '0655'

- name: "Generation du fichier de conf initial de pgadmin "
  template:
    src: "servers.json.j2"
    dest: /home/{{ ansible_user }}/servers.json
    mode: '0655'

- name: "Vérification de la création du fichier docker-compose"
  stat:
    path: /home/{{ ansible_user }}/docker-compose-pgadmin.yml
  register: result

- name: "Afficher le résultat de la vérification"
  debug:
    var: result

- name: "Lister le contenu du répertoire home"
  command: "ls -la /home/{{ ansible_user }}"
  register: ls_result

- name: "Afficher le contenu du répertoire home"
  debug:
    var: ls_result

- name: "Vérification de l'existence du fichier avant déploiement"
  stat:
    path: /home/{{ ansible_user }}/docker-compose-pgadmin.yml
  register: final_check

- name: "Afficher la vérification finale"
  debug:
    var: final_check

- name: "Déploiement du docker-compose-pgadmin.yml"
  shell: "/usr/local/bin/docker-compose -f /home/{{ ansible_user }}/docker-compose-pgadmin.yml up -d"
  args:
    chdir: /home/{{ ansible_user }}
  when: final_check.stat.exists
